model:
  name: shortestpath_5x5

data:
  name: shortestpath_5x5
  num_data: 250

runner:
  num_epochs: 5
  seed: 5
  use_wandb: false
  main_metric: rel_regret
  save_best: true
  experiments_folder: 'results/'

problem:
  train_ratio: 0.0833
  val_ratio: 0.0833
  compute_optimal_objectives: true
  compute_optimal_decisions: true
  standardize_features: true
  seed: 5

decision_maker:
  name: pfl
  learning_rate: 0.005
  batch_size: 32
  device_str: cpu
  predictor_str: MLP
  loss_function_str: mse
  predictor_kwargs:
    size: 256
    num_hidden_layers: 2
    output_activation: identity
