name: Publish Python package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Build package
        run: uv build --sdist --wheel

      - name: Publish to TestPyPI (main branch)
        if: github.ref == 'refs/heads/main'
        run: uv publish --repository testpypi
        env:
          UV_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}

      - name: Publish to PyPI (tagged release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: uv publish
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
